### ISSUE TITLE
template linter / formatter

### ISSUE THREAD

**Issue by jonathanhouge** [michael-awe/django-template#11]
hello! i recently used this repo as the basis for a school project (so thank you very much!) and, post-graduation in an attempt to keep my skills up, i've been wanting to add new functionality. i noticed that prettier, the vscode extension, doesn't understand django template tags and thus, can break html files when trying to format them. enter: https://github.com/djlint/djLint!

i think this could be a very helpful addition to 'requirements.txt' especially given that it took a bit of research to find it. wanted to share! thanks again for sharing this work with all!

**Comment by michael-awe** [comment]
hi there! thanks so much for the recommendation. i've just added it to the repo :)

**Comment by jonathanhouge** [comment]
you're welcome! :)
